stages:
  - test

api_test:
  stage: test
  image: node:20
  before_script:
    - apt-get update && apt-get install -y curl
    - npm install -g newman
    - npm install
  script:
    - node src/app.js &
    - sleep 2
    - newman run ./tests/TP.postman_collection.json
